version: "3.9"
services:
<<<<<<< HEAD
  api:
    build: .
    ports:
      - "5000:5000"
  web:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"


    
=======
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
>>>>>>> a231efc813de10c744e213dc36568df6b3a35120
